### ISSUE TITLE
Basic Stock Trend Display

### ISSUE THREAD

**Issue by mpeng8** [mpeng8/PyTrade#26]
## Story/Task Details
- [ ] Continue working on the stock price display so that on the dashboard page, the user can see the trend of chosen stock.

## Acceptance Scenarios

Given: A registered user is in the dashboard page
When: the user clicks on the stock display
Then: the user should be able to see the display of stock price

## Done Done Criteria
Without any interruption of previous work, the development should run without any error.

**Comment by mpeng8** [comment]
branch:iss26_stockDisplay_update

**Comment by mpeng8** [comment]
I have some problems that need unanimous agreement.

-  When the user clicks the stock, what is the default timeline for the stock price display? 

- Right now, my data comes from the free dataset on quandl, in JSON format. For the prediction feature, Yihan said that the output format will be pandas.dataFrame. I think that we need someone to work on the data format translation in the next sprint cycle.

- Stock List: This should be on the top priority for next sprint cycle. Search API need to be investigated and chosen. (Assigned to Mingjun for Sprint 3)

- For user connection, maybe instead of follow & unfollow users, the user should be able to search a certain user by username, and view his/her stock list and then add his/her stock list to the user's own.(Assigned to Mingjun for Sprint3)

- Trending news, if no one wants to do this, we should remove this in sprint 2.(Already did)

**Comment by mxie33** [comment]
I've fixed some bugs that appeared because the origin UI javascript conflicts with new features using d3.js and jqeury.js.

The problems occurred: 
Some script are not working such as logout bar cannot popout.
The menu bar on the left cannot be toggled.

The problems solved:
Javascript for logout bar can now be popped when clicking the arrow on the right of user profile picture.
Stock prices new features are maintained.
